version: "3"

vars:
  # Evaluates "date" using Task's internal POSIX interpreter
  BUILD_DATE:
    sh: date +%Y-%m-%d_%H-%M-%S

tasks:
  audit:
    desc: "Run quality control checks"
    deps: [test, generate]
    cmds:
      - go mod tidy -diff
      - go mod verify
      - test -z "$(gofmt -l .)"
      - go vet ./...
      - go fix -diff ./...
      - go tool -modfile=tools/go.mod deadcode -test ./...
      - go tool -modfile=tools/go.mod govulncheck ./...
      - go tool -modfile=tools/go.mod scc
      - golangci-lint run

  generate:
    desc: "Run code generation"
    cmds:
      - go generate ./...

  gosec:
    desc: "Run security static analysis on the module using go tool"
    cmds:
      - go tool -modfile=tools/go.mod gosec ./...

  test:
    desc: "Run the test suite"
    cmds:
      - go test -race -cover ./...
